# Generated by Django 2.1.5 on 2019-02-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190202_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecategory',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articlecategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='articlemedia',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articlemedia',
            old_name='media_id',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parent_category_id',
            new_name='parent_category',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='type_id',
            new_name='type',
        ),
    ]
