# Generated by Django 2.1.5 on 2019-02-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190202_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='teaser_text',
            field=models.TextField(max_length=500),
        ),
    ]
