# Generated by Django 2.1.5 on 2019-02-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190202_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
