# Generated by Django 2.1.5 on 2019-02-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190203_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
