# Generated by Django 2.1.5 on 2019-03-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190203_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quote',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_headline',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
