# Generated by Django 2.1.5 on 2019-03-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190317_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleElementPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(max_length=3)),
                ('headline', models.IntegerField(max_length=3)),
                ('sub_headline', models.IntegerField(max_length=3)),
                ('main_text', models.IntegerField(max_length=3)),
                ('teaser_text', models.IntegerField(max_length=3)),
                ('quote', models.IntegerField(max_length=3)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
    ]
