# Generated by Django 2.1.5 on 2019-03-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_articleelementposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleelementposition',
            name='created',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='articleelementposition',
            name='updated',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='articleelementposition',
            name='author',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='articleelementposition',
            name='headline',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='articleelementposition',
            name='main_text',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='articleelementposition',
            name='quote',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='articleelementposition',
            name='sub_headline',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='articleelementposition',
            name='teaser_text',
            field=models.IntegerField(default=10),
        ),
    ]
